### ISSUE TITLE
 php blend -v not working

### ISSUE THREAD

**Issue by bloodcrow777** [LippertComponents/Blend#4]
The command php blend -v does not work as expected, brings up the following errors:

`
/paas/c0094/www/core/components/blend $ php blend -v
Could not open input file: blend
/paas/c0094/www/core/components/blend $ cd vendor/bin/
/paas/c0094/www/core/components/blend/vendor/bin $ php blend -v

In ArgvInput.php line 200:

  [Symfony\Component\Console\Exception\RuntimeException]
  The "-v" option does not exist.

Exception trace:
 Symfony\Component\Console\Input\ArgvInput->addShortOption() at /www/core/components/blend/vendor/symfony/console/Input/ArgvInput.php:108
 Symfony\Component\Console\Input\ArgvInput->parseShortOption() at /www/core/components/blend/vendor/symfony/console/Input/ArgvInput.php:84
 Symfony\Component\Console\Input\ArgvInput->parse() at /www/core/components/blend/vendor/symfony/console/Input/Input.php:55
 Symfony\Component\Console\Input\Input->bind() at /www/core/components/blend/vendor/symfony/console/Command/Command.php:210
 Symfony\Component\Console\Command\Command->run() at /www/core/components/blend/vendor/symfony/console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /www/core/components/blend/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /www/core/components/blend/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /www/core/components/blend/vendor/lci/blend/bin/blend:5

list [--raw] [--format FORMAT] [--] [<namespace>]
`

If you type --version it works, as well as capital -V it works.

`
/paas/c0094/www/core/components/blend/vendor/bin $ php blend --version
Blend Console 1.0.0 beta9
`

**Comment by bloodcrow777** [comment]
Right now -V or --version works. However @jgulledge19 intended for it to work with lowercase -v as well. Just making it an issue for future reference when we have time to address. =)

**Comment by jgulledge19** [comment]
@bloodcrow777 I believe that lower case v is more commonly used in Symfony Console for verbose. See https://symfony.com/doc/current/console/verbosity.html. Will keep with that recommendation, so capital V for version. I have not implemented verbose output as of yet.
